### PR TITLE
Update spring to version 2.x.x

### PR DESCRIPTION
**Pull request by xurror**

### CODE REVIEW

**Comment by aasaru** [comment]
Hi!
Are you working together with @maektwain or you don't know him?

He is working on same thing, please see the comments I wrote him:
https://github.com/apache/fineract-cn-anubis/pull/11#issuecomment-616339182

We need the same thing here - please send your PR towards branch spring_boot_2

Thanks!

**Comment by maektwain** [comment]
> Hi!
> Are you working together with @maektwain or you don't know him?
> 
> He is working on same thing, please see the comments I wrote him:
> https://github.com/apache/fineract-cn-anubis/pull/11#issuecomment-616339182
> 
> We need the same thing here - please send your PR towards branch spring_boot_2
> 
> Thanks! 

We are already coordinating with each other. Let's divide more work. 

What do you suggest? @aasaru

**Comment by maektwain** [comment]
Hey @xurror did you face any existing API deprecation problem.?

**Comment by xurror** [comment]
Nope

**Comment by xurror** [comment]
Everything worked as before

**Comment by xurror** [comment]
There are 2 tests that fail here.

**Comment by xurror** [comment]
I'll try to fix them and update this

**Pull request closed without merging**
